baseURL = "https://ksriram.dev"
languageCode = "en-us"
title = "Kalyan's Blog"
theme = "re-terminal"

[params]
themeColor = "green"

[params.logo]
logoText = "/home/kalyan"

[menu]

[[menu.main]]
identifier = "research"
name = "Research"
url = "/research"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 20

[[menu.main]]
identifier = "teaching"
name = "Teaching"
url = "/teaching"
weight = 30

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 40

[[menu.main]]
identifier = "pictures"
name = "Pictures"
url = "/pictures"
weight = 50

# [[menu.main]]
# identifier = "resources"
# name = "Resources"
# url = "/resources"
